INSERT INTO `countries` (`id`, `name`, `code`) VALUES
	(1, 'GERMANY', 'GK'),
	(2, 'BRITAIN', 'UB'),
	(3, 'FRANCE', 'FF'),
	(4, 'SPAIN', 'SK'),
	(5, 'CZECH REP', 'CZ'),
	(6, 'ITALY', 'IJ'),
	(7, 'DENMARK', 'DB'),
	(8, 'AUSTRIA', 'AK'),
	(9, 'RUSSIA', 'UR'),
	(10, 'SWEDEN', 'ST'),
	(11, 'CANADA', 'UD'),
	(12, 'HUNGARY', 'HG'),
	(13, 'IRELAND', 'IG'),
	(14, 'SOUTH AFRICA', 'SH'),
	(16, 'CROATIA', 'CK'),
	(17, 'USA', 'US'),
	(18, 'PORTUGAL', 'PH'),
	(19, 'LIBERIA', 'LC'),
	(20, 'POLAND', 'PG'),
	(21, 'PAPUA NEW GUINEA', 'PC'),
	(22, 'BELGIUM', 'BD'),
	(23, 'NETHERLANDS', 'NB'),
	(24, 'NORWAY', 'NQ'),
	(25, 'MONGOLIA', 'MU'),
	(26, 'COLOMBIA', 'CJ'),
	(27, 'MOZAMBIQUE', 'MK'),
	(28, 'CAMBODIA', 'CA'),
	(29, 'AZERBAIJAN', 'AZ'),
	(30, 'CAMEROON', 'CU'),
	(31, 'MALAGASY REP.', 'MA'),
	(32, 'SOUTH KOREA', 'KB'),
	(33, 'IVORY COAST', 'IK'),
	(34, 'EGYPT', 'EB'),
	(35, 'JORDAN', 'JC'),
	(36, 'LEBANON', 'LB'),
	(37, 'MALAYSIA OR QATAR', 'MB'),
	(38, 'MEXICO', 'MH'),
	(39, 'TANZANIA', 'TC'),
	(40, 'SENEGAL', 'SX'),
	(41, 'ARMENIA', 'AV'),
	(42, 'SEYCHELLES', 'SD'),
	(43, 'IRAQ', 'IF'),
	(44, 'BOSNIA', 'BX'),
	(45, 'BAHRAIN', 'BB'),
	(46, 'KUWAIT', 'KC'),
	(47, 'SAUDI ARABIA', 'SC'),
	(48, 'UNITED AE', 'EM'),
	(49, 'OMAN', 'MS'),
	(51, 'CAPE VERDE', 'CD'),
	(52, 'ROMANIA', 'RB'),
	(53, 'SWITZERLAND', 'SU'),
	(54, 'MALAWI', 'MD'),
	(55, 'SURINAME', 'SS'),
	(56, 'PERU', 'PE'),
	(57, 'BOLIVIA', 'BG'),
	(58, 'KENYA', 'KA'),
	(59, 'GHANA', 'GC'),
	(60, 'NIGERIA', 'NM'),
	(61, 'MOLDOVA', 'MV'),
	(62, 'GRENADA', 'GN'),
	(63, 'GEORGIA', 'GR'),
	(64, 'SRI LANKA', 'CF'),
	(65, 'SLOVENIA', 'SF'),
	(66, 'BURKINA FASO', 'TH'),
	(67, 'FINLAND', 'FD'),
	(68, 'PARAGUAY', 'PD'),
	(69, 'CHILE', 'CG'),
	(70, 'ALGERIA', 'AD'),
	(71, 'UKRAINE', 'UK'),
	(72, 'BRAZIL', 'BH'),
	(73, 'ARGENTINA', 'AG'),
	(74, 'GREECE', 'GF'),
	(75, 'BELARUS', 'BV'),
	(76, 'MACEDONIA', 'MY'),
	(77, 'BRUNEI', 'BR'),
	(78, 'URUGUAY', 'UC'),
	(79, 'ANGOLA', 'AF'),
	(80, 'GIBRALTAR', 'GD'),
	(82, 'MALTA', 'MC'),
	(83, 'MAURITIUS', 'MF'),
	(84, 'LITHUANIA', 'LH'),
	(85, 'LATVIA', 'LG'),
	(86, 'ESTONIA', 'EF'),
	(87, 'ETHIOPIA', 'ET'),
	(88, 'LAOS', 'LA'),
	(89, 'SLOVAK REP', 'SW'),
	(90, 'ANDORRA', 'AE'),
	(91, 'TURKEY', 'TG'),
	(92, 'HONG KONG', 'HF'),
	(93, 'SINGAPORE', 'MT'),
	(94, 'TAIWAN', 'TB'),
	(95, 'JAPAN', 'JB'),
	(96, 'NEW ZEALAND', 'NK'),
	(97, 'TAHITI', 'TA'),
	(98, 'NEW CALEDONIA', 'NG'),
	(99, 'KAZAKHSTAN', 'KZ'),
	(100, 'BULGARIA', 'BN'),
	(101, 'CYPRUS', 'CS'),
	(102, 'PUERTO RICO_CAYMAN ISLAND', 'PM'),
	(103, 'BARBADOS', 'BC'),
	(104, 'ALBANIA', 'AC'),
	(105, 'AUSTRALIA', 'AJ'),
	(106, 'BERMUDA', 'BE'),
	(107, 'REP_DOMINICANA', 'DD'),
	(108, 'ECUADOR', 'EA'),
	(109, 'MOROCCO', 'MJ'),
	(110, 'TUNISIA', 'TF'),
	(111, 'ZAMBIA', 'ZB'),
	(112, 'ZIMBABWE', 'ZX'),
	(113, 'LYBIA', 'LY'),
	(114, 'ISRAEL', 'IH'),
	(115, 'ARUBA', 'AR'),
	(116, 'GABON', 'GA'),
	(117, 'SERBIA & MONTENEGRO', 'YB'),
	(118, 'SIERRA LEONE', 'SE'),
	(9999, 'UNKNOWN', 'UNK'),
	(10001, 'VENEZUELA', 'VA'),
	(10002, 'MALAYSIA/QATAR', 'QA'),
	(10003, 'CURACAO', 'AL'),
	(10006, 'BELIZE', 'BK'),
	(10007, 'JAMAICA', 'JA'),
	(10008, 'TRINIDAD', 'TE');
