
START TRANSACTION;

INSERT INTO holds (code, name, priority, active) VALUES ('333/334', '333/334', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('AC', 'AWAITING CUSTOMS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('ALFOMBRILLA', 'ALFOMBRILLA', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('ALMACEN', 'ALMACEN', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('AW', 'AWAITING PDI', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('AZ', 'STOLEN', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('B&H', 'BATCH AND HOLD', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('BAHO', 'Batch & Hold', 2, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('BARCOESPECIAL', 'BARCO ESPECIAL USA', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('BATERIA', 'BATERIA', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('BITURBO', 'BITURBO', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('BK2PLNT', 'Back to Plant Request', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('BORN_SINTAX', 'BORN_SINTAX', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('BP', 'BAK TO PLANT', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('BP_ABOLLADURA', 'BP_ABOLLADURA', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('BP_INTEGRALE', 'BP_INTEGRALE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('BP_RASER_21', 'BP_RASER_21', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('BS', 'DEALER STOCKED', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('BUFFER', 'BUFFER', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('BW', 'MISSING DOCUMENTS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CA', 'DAMAGED, NOT SHIPPABLE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CAMBIO_DEALER', 'CAMBIO_DEALER', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CAMBIO_TRANSPORTE', 'CAMBIO_TRANSPORTE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CAMPAIGN', 'Quality Campaign', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CAMPAIGN28', 'Quality Campaign 28', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CAMPAIGN4711', 'Quality Campaign 4711', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CARGADORES', 'CARGADORES', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CC', 'AW VESSEL DEPARTURE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CD391_RUIDO_2FILA', 'CD391_RUIDO_2FILA', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CF', 'CUSTOMS FINISHED', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CHESTE', 'CHESTE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CHIN', 'CHIN', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CHOUT', 'CHOUT', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CMP_P12', 'CMP_P12', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('COCHE_DANIEL_RUIZ', 'COCHE_DANIEL_RUIZ', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('COLOGNE', 'COLOGNE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('COLOGNE_WWL', 'COLOGNE_WWL', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CREMALLERA', 'CREMALLERA', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CREMALLERA_FORD', 'CREMALLERA_FORD', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CREMALLERA_INTEGRALE', 'CREMALLERA_INTEGRALE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CREMALLERA_KH', 'CREMALLERA_KH', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CT', 'CUSTOMS CLEARANCE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CUCL', 'Customs Clearance', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('CUSTOMS', 'CUSTOMS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('DAMAGES', 'DAMAGE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('DD_LAUNCH', 'DROW DOWN', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('DEFECTO_CALIDAD', 'DEFECTO_CALIDAD', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('DISENGAGEMENT', 'disengagement', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('DROP', 'DROP', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('DW10_CHESTE', 'DW10_CHESTE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('ERROR_TRANSPORTE', 'ERROR_TRANSPORTE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('ESP', 'PREGUNTAR', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('EW', 'EX WORKS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('FAURECIA', 'FAURECIA', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('FCPA-ST', 'FPCA-ST', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('FH', 'FINANCIAL HOLD', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('GATE_RELEASE_MISSING', 'Gate Release Missing', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('GEFCO_ISLANDS', 'GEFCO_ISLANDS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('GERENCIA', 'GERENCIA', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('GL', 'LAUNCH HOLD', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('GUARD', 'GUARD', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('GUSTAVSBURG_SETRAM', 'GUSTAVSBURG_SETRAM', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('HANDBOOK', 'HANDBOOK', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('HCM', 'HCM', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('HL', 'HOMOLOGATION', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('HM', 'MANUFACTURING HOLD', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('HM_QC', 'HM QUALITY CAMPAIGN', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('HN', 'NSC HOLD', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('HT', 'TRAFFIC HOLD', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('I9', 'I9', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('ICA', 'ICA', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('ILT3', 'ILT3', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('INSPECCION', 'INSPECCION', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('INSPECCION_CUBA', 'INSPECCION_CUBA', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('INSPECCION_RUIDO_INTEGRALE', 'INSPECCION_RUIDO_INTEGRALE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('INSPECCION_RUIDO_LEFTDOOR', 'INSPECCION_RUIDO_LEFTDOOR', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('INVESTIGACION_PHEV', 'INVESTIGACION_PHEV', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('K1', 'CONTROLLED DELIVERY', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('KH_ACEITE', 'KH_ACEITE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('KSK', 'launch connect', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('LAUNCH', 'LAUNCH', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('LAUNCH-CHESTE', 'LAUNCH-CHESTE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('LKA', 'LKA', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('MANU', 'MANU', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('MARATON', 'MARATON', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('MISI', 'Missing Information', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('MISI_COLOUR', 'Missing Colour', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('MISI_COLOUR_EOC', 'Missing Colour EOC', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('MISI_DEST', 'Missing Destination', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('MISI_MARKET', 'Missing Market', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('MISI_MODEL', 'Missing Model', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('MISI_VIN_LENGTH', 'Incorrect length of VIN', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('MISSING_SD', 'MISSING SD', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('MISSINGINVOICES', 'MISSINGINVOICES', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('MOD_LIVORNO', 'MOD_LIVORNO', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('MONDEO_FECHAS', 'MONDEO_FECHAS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('MP1', 'MP1', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('MP2', 'MP2', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NA', 'VEHICLE IN MODIFICATION PROCESS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NC', 'OUT OF LOCATION', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NEUSS_SETRAM', 'NEUSS_SETRAM', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NEUSS_WWL', 'NEUSS_WWL', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NGAVS_REJECTED', 'NGAVS Rejected', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NL', 'MISSING LABEL', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NO_INFORMAR', 'NO INFORMAR', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NO_OK', 'NO_OK', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NO_TRANS_CHECK_RASER', 'NO_TRANS_CHECK_RASER', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NO_TRANSPORTAR', 'NO TRANSPORTAR', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NO_TRANSPORTAR_A_CHESTE', 'NO_TRANSPORTAR_A_CHESTE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NO_TRANSPORTAR_ACC', 'NO_TRANSPORTAR_ACC', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NO_TRANSPORTAR_BULKHEAD', 'NO_TRANSPORTAR_BULKHEAD', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NO_TRANSPORTAR_C520_CONSOLA', 'NO_TRANSPORTAR_C520_CONSOLA', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NO_TRANSPORTAR_CD7PLAZAS', 'NO_TRANSPORTAR_CD7PLAZAS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NO_TRANSPORTAR_KH', 'NO_TRANSPORTAR_KH', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NO_TRANSPORTAR_NO_OKTB', 'NO_TRANSPORTAR_NO_OKTB', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NO_TRANSPORTAR_OTE', 'NO_TRANSPORTAR_OTE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NO_TRANSPORTAR_OXIDO', 'NO_TRANSPORTAR_OXIDO', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NO_TRANSPORTAR_PABLO', 'NO_TRANSPORTAR_PABLO', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NO_TRANSPORTAR_PABLO_AK', 'NO_TRANSPORTAR_PABLO', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NO_TRANSPORTAR_QUEMADAS', 'NO_TRANSPORTAR_QUEMADAS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NO_TRANSPORTAR_TECHOPANORAMICO', 'NO_TRANSPORTAR_TECHOPANORAMICO', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NO_TRANSPORTAR_VICENTE', 'NO_TRANSPORTAR_VICENTE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NO_TRANSPORTAR_VIN_ERRONEO', 'NO_TRANSPORTAR_VIN_ERRONEO', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NO_TRANSPORTAR_WRAPGUARD', 'NO_TRANSPORTAR_WRAPGUARD', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NOCHESTE', 'NOCHESTE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NOT_HANDLE', 'NOT_HANDLE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('NP', 'MISSING PARTS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('OK_LINE', 'OK LINE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('OK2BUY', 'OK 2 Buy', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('OTE', 'OTE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('OTE_KM', 'OTE_KM', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('PECOVASA', 'PECOVASA', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('PEGATINA', 'PEGATINA', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('PENDIENTE', 'PENDIENTE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('PP', 'PP', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('Q5', 'NSC/ COMPANY STOCK', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('QD', 'STRIKE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('QLS_CARPA', 'DEFECTO_CARPA', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('QM', 'BREAK DOWN, NOT SHIPPABLE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('QM_INTERCOOLER', 'QM_INTERCOOLER', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('QQ', 'QUALITY HOLD', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('RACKS', 'RACKS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('RETENCION_PRE_ESTACION_7', 'RETENCION_PRE_ESTACION_7', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('RUIDO_LEFTDOOR', 'RUIDO_LEFTDOOR', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('SAARLOUIS_WWL', 'SAARLOUIS_WWL', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('SALZBURG_SINTAX', 'SALZBURG_SINTAX', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('SPECIAL_OPERATION_JAN_15', 'SPECIAL_OPERATION_JAN_15', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('SPECIAL_OPERATION_TOBIAS', 'SPECIAL_OPERATION_TOBIAS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('SPOILER', 'SPOILER', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('ST', 'SHIP TO CHESTE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TACO_MOTOR', 'TACO_MOTOR', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TAPITA', 'TAPITA', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TC', 'To Cheste', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH', 'TECHNICAL HOLD', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ C346_BOLTS_BROKEN', 'TH_ C346_BOLTS_BROKEN', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ C420_TRAN _NTRANSIT', 'TH_ C420_TRAN _NTRANSIT', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ C520_2.5_IVCT', 'TH_ C520_2.5_IVCT', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ C520_CALIBRATION', 'TH_ C520_CALIBRATION', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ C520_DW10F_DTC', 'TH_ C520_DW10F_DTC', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ C520_FRONTDOOR', 'TH_ C520_FRONTDOOR', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ C520_PANORAMIC_ROOF', 'TH_  C520E–Grind_noise_ panoramic_roof', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ C520_PHYSICAL_VIN_ERRONEO', 'TH_ C520_PHYSICAL_VIN_ERRONEO', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ C520_TAILGATE_SPOILER', 'TH_ C520_TAILGATE_SPOILER', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ C520MCA PETROL PT', 'TH_ C520MCA PETROL PT', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ CD_TORNILLOBOMBA', 'TH_ CD_TORNILLOBOMBA FUEL', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ CD390/539 WITH VOLUMETRIC', 'TH_ CD390/539 WITH VOLUMETRIC', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ CD391_FOX', 'TH_ CD391_FOX', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ DW10_333_334', 'TH_ DW10_333_334', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ DW10F RHD CLUTCH LINE', 'TH_ DW10F RHD clutch line', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ EVRV NUT T', 'TH_ EVRV NUT T', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ GALAXY_3RD_ROW_SEAT', 'TH_ GALAXY_3RD_ROW_SEAT', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ KUGA (C520MCA) TYPE 2 KEY', 'TH_ KUGA (C520MCA) TYPE 2 KEY', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ REAR AXLE TOE LINK BRACKET', 'TH_ REAR AXLE TOE LINK BRACKET', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ STOP SHIP KUGA (C520) DUST', 'STOP SHIP KUGA (C520) Dust Shield Bent C520', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ TORSION_BEAM_WELDING', 'TH_ TORSION_BEAM_WELDING', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ V408N ICA', 'TH_ V408N ICA', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ WATER_LEAKS_C520', 'TH_ WATER_LEAKS_C520', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_ WVTA_MARKETS', 'TH_ WVTA_MARKETS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_10.08', 'TH_10.08', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_361', 'TH_361', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_7SEATS', 'TH_7SEATS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_AS_MARK', 'TH_AS_MARK', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_BRACKET', 'TH_BRACKET', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_C344_DV5_115PS', 'TH_C344_DV5_115PS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_C4.2_HEADLAMP', 'TH_C4.2_HEADLAMP', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_C520 DVW10F/MMT6', 'TH_C520 DVW10F/MMT6', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_C520 WITH ICE PACK 26', 'TH_C520 WITH ICE PACK 26', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_C520_CLIMATE_ZONE', 'TH_C520_CLIMATE_ZONE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_C520_FRONT_BRAKE', 'TH_C520_Front_Brake', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_C520_GSO_MARKETS', 'TH_C520_GSO_MARKETS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_C520_MCA_TOWHOOK', 'TH_C520_MCA_TOWHOOK', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_C520_MMT6', 'TH_C520_MMT6', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_C520_RETRACTABLE_TOWBAR', 'TH_C520_RETRACTABLE_TOWBAR', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_C520_ST-LINE', 'TH_C520_ST-LINE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_C520_SYNC2_2016', 'TH_C520_SYNC2_2016', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_C520E DELAMINATION', 'TH_C520E delamination of chrome of door panel', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_C520E WITH DW10F OIL PAN LE', 'TH_C520E OIL PAN', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_C520E_DW10F_BOOST_PRESSURE', 'TH_C520E_DW10F_BOOST_PRESSURE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_C520MCA 2.0 GTDI', 'TH_C520MCA 2.0 GTDI', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_C520MCA_TITANIUM', 'TH_C520MCA_TITANIUM', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_C520MCA_VIGNALE', 'TH_C520MCA_VIGNALE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_C702-703-704', 'TH_C702-703-704', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_CD_REFRIGERANT', 'TH_CD_REFRIGERANT', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_CD390/539 RHD WITH HEATED S', 'TH_CD390/539 RHD with heated seats', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_CD390_CD539_HEADLAMPS', 'TH_CD390_CD539_HEADLAMPS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_CD390_SR_MASS_DAMPER', 'TH_CD390_SR_MASS_DAMPER', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_CD391 5 DR WITH PANO ROOF', 'TH_CD391 5 DR WITH PANO ROOF', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_CD391_MISMATCH', 'TH_CD391_MISMATCH', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_CD391_S&R NOISE', 'TH_CD391_S&R NOISE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_CD391_SYNC2_REBOOT', 'TH_CD391_SYNC2_REBOOT', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_CD391_WAGON_PAINT', 'TH_CD391_WAGON_PAINT', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_CD391_WIND_NOISE', 'TH_CD391_WIND_NOISE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_CD391E DW10F ECO', 'TH_CD391E DW10F ECO', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_CD391E RATTLE ON CIGAR', 'TH_ CD391E Rattle on cigar lighter', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_CD53&CD390_THIRD ROW', 'TH_CD53&CD390_THIRD ROW', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_CD539_FCSD_SPOILER', 'TH_Cd539_FCSD_SPOILER', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_CD539_LIGHTGATE_HANDLE', 'TH_CD539_LIGHTGATE_HANDLE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_CD539_SPOILER', 'TH_CD539_SPOILER', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_CONTINETAL', 'TH_CONTINETAL', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_DIRTYFUEL', 'TH_DIRTYFUEL', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_DV6_95PS', 'TH_DV6_95PS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_DV6_ENGINE', 'TH_DV6_ENGINE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_DW10 MONDEO', 'TH_DW10 MONDEO', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_DW10F OIL LEAK', 'TH_DW10F OIL LEAK', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_DW10F OIL PRESSURE SEN', 'TH_DW10F OIL PRESSURE SEN', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_INCORRECT_VIN', 'TH_INCORRECT_VIN', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_KUGA DW10 NO ICA', 'TH_Kuga DW10 no ICA', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_KUGA_LAMPS_NO_LED', 'TH_KUGA_LAMPS_NO_LED', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_MAGNETIC GREY COLOUR MISMAT', 'TH_MAGNETIC GREY COLOUR MISMAT', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_MISSING HOMOLOGATION', 'TH_MISSING HOMOLOGATION', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_MONDEO_CLUSTERS', 'TH_MONDEO_CLUSTERS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_PAINT_CONTAMINATION', 'TH_PAINT_CONTAMINATION', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_PROVISIONAL', 'TH_PROVISIONAL', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_RADIO_USB', 'TH_RADIO_USB', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_TH_ CD-CAR STEERING GEAR BO', 'TH_TH_ CD-CAR STEERING GEAR BO', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_THERMOSTATS', 'TH_THERMOSTATS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_TRIM_B_A', 'TH TRIM B-A', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_TTLM', 'TH_TTLM', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_UPPER CLUTCH LINE RATTLE', 'TH_UPPER CLUTCH LINE RATTLE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_V408  OIL PAN HEATSHI', 'TH_V408  OIL PAN HEATSHI', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_V408 KOMBI SWB PACKAGE', 'TH_V408 Kombi SWB w/ package tray', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_V408_DOHC', 'TH_V408_DOHC', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_V408_DV5_B6', 'TH_V408_DV5 and B6 due to Incorrect Lower Clutch Pipe', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_V408_ERROR_ST7', 'TH_V408_ERROR_ST7', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_V408_FOX', 'TH_V408_FOX', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_V408_LOW COST', 'TH_V408_LOW COST', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_V408_MTX75', 'TH_V408_MTX75', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_V408_PAINT', 'TH_V408_PAINT', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_V408_TURKEY', 'TH_V408_TURKEY', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_V408_WIND_NOISE', 'TH_V408_WIND_NOISE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_V408_YUAKAWA_REAR_CAMERA', 'TH_V408_YUAKAWA_REAR_CAMERA', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_V408-BYCAJ', 'TH_V408-BYCAJ', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_V408N_ICA 2.5 DOHC', 'TH_V408N_ICA 2.5 DOHC', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TH_V408N_MFD4_“YUAKAWA”', 'V408N_MFD4_“Yuakawa”', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TL', 'TOTAL LOSS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TOMAS', 'TOMAS', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TONGEREN_HELICAR', 'TONGEREN_HELICAR', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TOTAL_LOST', 'TOTAL_LOST', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TOWBAR', 'TOW-BAR', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TRANSFESA', 'TRANSFESA', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TRANSPORTE', 'TRANSPORTE', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TREN', 'TREN', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TRM', 'TRM', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TROQUELADO', 'TROQUELADO', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('TT', 'TT', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('UL', 'UNKNOWN LOCATION', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('VEDAT', 'vedat', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('VICEN', 'VICEN', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('VIN_ERRONEO', 'VIN_ERRONEO', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('VQC', 'VQC', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('WHITE_PLATINUM', 'WHITE_PLATINUM', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('WOERTH_SETRAM', 'WOERTH_SETRAM', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('XZ', 'WEATHER HOLD', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('Y', 'Delaycode Y', 2, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('Z_IN', 'Z_IN', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('Z_OUT', 'Z_OUT', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('ZEN', 'ZENDER', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('ZULPICH_WWL', 'ZULPICH_WWL', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('BATCH_HOLD', 'B&H', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('MANUALES', 'MANUALES', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('PEPITO', 'pepito', 1, 1);
INSERT INTO holds (code, name, priority, active) VALUES ('QM_ABOLLADURA_LATERAL', 'QM_ABOLLADURA_LATERAL', 1, 1);


INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'AC'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'ALFOMBRILLA'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'ALFOMBRILLA'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'AW'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'AZ'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'B&H'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'BAHO'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'BATERIA'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'BATERIA'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'BK2PLNT'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'BP'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'BS'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'BUFFER'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'BUFFER'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'BW'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CA'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CA'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CAMBIO_DEALER'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CAMBIO_DEALER'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CAMBIO_TRANSPORTE'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CAMPAIGN'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CAMPAIGN28'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CAMPAIGN4711'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CARGADORES'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CARGADORES'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CC'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CF'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CHIN'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CHIN'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CHOUT'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CHOUT'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CMP_P12'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'COCHE_DANIEL_RUIZ'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'COCHE_DANIEL_RUIZ'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CT'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CUCL'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CUSTOMS'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'CUSTOMS'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'DAMAGES'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'DAMAGES'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'DD_LAUNCH'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'DD_LAUNCH'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'DISENGAGEMENT'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'DISENGAGEMENT'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'DROP'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'DW10_CHESTE'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'ERROR_TRANSPORTE'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'ERROR_TRANSPORTE'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'ESP'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'ESP'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'EW'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'FAURECIA'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'FAURECIA'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'FCPA-ST'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'FCPA-ST'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'FH'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'GATE_RELEASE_MISSING'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'GATE_RELEASE_MISSING'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'GL'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'GUARD'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'GUARD'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'HCM'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'HCM'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'HL'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'HM'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'HM_QC'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'HN'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'HT'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'I9'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'ILT3'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'ILT3'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'INSPECCION'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'INSPECCION'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'INSPECCION_CUBA'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'INSPECCION_CUBA'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'INVESTIGACION_PHEV'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'INVESTIGACION_PHEV'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'K1'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'KSK'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'KSK'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'LAUNCH'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'LAUNCH'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MANU'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MANU'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MANUALES'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MANUALES'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MARATON'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MISI'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MISI'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MISI_COLOUR'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MISI_COLOUR'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MISI_COLOUR_EOC'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MISI_COLOUR_EOC'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MISI_DEST'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MISI_DEST'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MISI_MARKET'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MISI_MARKET'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MISI_MODEL'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MISI_MODEL'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MISI_VIN_LENGTH'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MISI_VIN_LENGTH'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MISSINGINVOICES'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MOD_LIVORNO'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MONDEO_FECHAS'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'MONDEO_FECHAS'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NA'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NC'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NGAVS_REJECTED'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NL'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_INFORMAR'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANS_CHECK_RASER'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANS_CHECK_RASER'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANSPORTAR'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANSPORTAR'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANSPORTAR_A_CHESTE'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANSPORTAR_A_CHESTE'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANSPORTAR_ACC'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANSPORTAR_BULKHEAD'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANSPORTAR_C520_CONSOLA'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANSPORTAR_C520_CONSOLA'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANSPORTAR_CD7PLAZAS'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANSPORTAR_KH'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANSPORTAR_NO_OKTB'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANSPORTAR_OTE'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANSPORTAR_OXIDO'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANSPORTAR_PABLO'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANSPORTAR_PABLO_AK'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANSPORTAR_QUEMADAS'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANSPORTAR_TECHOPANORAMICO'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANSPORTAR_VICENTE'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANSPORTAR_VIN_ERRONEO'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NO_TRANSPORTAR_WRAPGUARD'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NOCHESTE'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NOCHESTE'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NOT_HANDLE'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'NP'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'OK_LINE'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'OK_LINE'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'OK2BUY'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'OTE'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'OTE_KM'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'PECOVASA'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'PEGATINA'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'PEGATINA'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'PEPITO'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'PEPITO'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'PP'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'PP'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'Q5'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'QD'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'QD'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'QLS_CARPA'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'QM'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'QQ'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'RACKS'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'RETENCION_PRE_ESTACION_7'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'RETENCION_PRE_ESTACION_7'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'RUIDO_LEFTDOOR'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'SALZBURG_SINTAX'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'SPECIAL_OPERATION_JAN_15'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'TAPITA'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'TAPITA'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'TH'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'TH'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'TH_CD391E RATTLE ON CIGAR'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'TH_CD391E RATTLE ON CIGAR'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'TH_TH_ CD-CAR STEERING GEAR BO'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'TH_TH_ CD-CAR STEERING GEAR BO'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'TH_TRIM_B_A'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'TL'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'TL'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'TOMAS'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'TOMAS'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'TRANSFESA'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'TROQUELADO'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'TROQUELADO'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'TT'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'TT'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'UL'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'VEDAT'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'VEDAT'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'VICEN'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'VICEN'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'VIN_ERRONEO'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'VIN_ERRONEO'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'WHITE_PLATINUM'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'XZ'), (SELECT id FROM conditions WHERE name = 'NO_RELEASE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'XZ'), (SELECT id FROM conditions WHERE name = 'PLANNABLE'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'Y'), (SELECT id FROM conditions WHERE name = 'DISPATCH_STOP'));
INSERT INTO holds_conditions (hold_id, condition_id) VALUES ((SELECT id FROM holds WHERE CODE = 'ZEN'), (SELECT id FROM conditions WHERE name = 'TOTAL_STOP'));


COMMIT;
